Add scripts to configure Elasticsearch data source
sassoftware/viya4-monitoring-kubernetes pull request #308
Opened 2022-03-02 21:50 UTC by cumcke

- Created two scripts to configure the Elasticsearch data source in Grafana (one for cluster and one for tenant).
- Currently, the tenant admin that's created with the logging onboarding scripts do not have enough permission so, for the time being, we either need to either:
- - Update the permission of the tenant admin user to include **indices:admin/mappings/get** for **viya_logs-* ** in order for it to work as intended (will be creating new users for these scripts in a later release.
- - Use admin user ID.

I also used this opportunity to update a multi-tenant Prometheus YAML file to include the correct URL (v4m-prometheus-__TENANT__:9090).

2022-03-03 13:50 UTC, BryanEllington requested changes

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_cluster.sh
> +  log_verbose "Monitoring found in $MON_NS namespace.  Continuing."
Seems like this should be a log_debug message

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_cluster.sh
> +  log_verbose "Logging found in $LOG_NS namespace.  Continuing."
As above, should this be log_debug?

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_cluster.sh
> +  cp -R monitoring/grafana-datasource-es.yaml $monDir/grafana-datasource-es.yaml
don't need -R

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_cluster.sh
> +# Pull Elasticsearch password in temp directory file
"in temp directory file" is incorrect here. It's just an in-memory variable

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_cluster.sh
> +log_debug "Replacing logging namespace for files in [$monDir]"
Suggested message: "Replacing variables in $monDir/grafana-datasource-es.yaml"

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_cluster.sh
> +kubectl delete pods -n $tenantNS -l "app.kubernetes.io/instance=v4m-grafana-acme"
This is the cluster script, so it should be `-n $MON_NS -l "app.kubernetes.io/instance=v4m-grafana"`

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_cluster.sh
> +kubectl -n $tenantNS wait pods --selector app.kubernetes.io/instance=v4m-grafana-acme --for condition=Ready --timeout=2m
Same thing - use `$MON_NS` and `v4m-grafana`

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_tenant.sh
> +    log_error "No monitoring components found in the $tenantNS namespace.  Monitoring needs to be deployed in this namespace in order to configure Elasticsearch with this script.";
Split into two log_error messages on the sentence boundary.

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_tenant.sh
> +    log_verbose "Monitoring deployment was found for the $tenant tenant in the $tenantNS namespace.  Continuing."
log_debug

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_tenant.sh
> +# Verify that the password is correct?
Either implement the check or remove the comment

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_tenant.sh
> +tenantDir=$TMP_DIR/$VIYA_TENANT
There is no `$VIYA_TENANT` variable here - use `$tenant`

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_tenant.sh
> +log_debug "Replacing logging namespace for files in [$tenantDir]"
Change message to `Replacing variables in $tenantDir/grafana-datasource-es.yaml`

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_tenant.sh
> +log_info "Provisioning Elasticsearch data source for Grafana"
Message: Provisioning Elasticsearch data source for [$tenantNS/$tenant] instance of Grafana

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_tenant.sh
> +kubectl delete pods -n $tenantNS -l "app.kubernetes.io/instance=v4m-grafana-acme"
Hard-coded `acme` here. Use `$tenant`

2022-03-03 13:50 UTC, BryanEllington commented on monitoring/bin/create_elasticsearch_datasource_tenant.sh
> +kubectl -n $tenantNS wait pods --selector app.kubernetes.io/instance=v4m-grafana-acme --for condition=Ready --timeout=2m
Replace hard-coded `acme`

2022-03-03 21:09 UTC, gsmith-sas commented on monitoring/bin/create_elasticsearch_datasource_tenant.sh
> +cp -R monitoring/grafana-datasource-es.yaml $tenantDir/grafana-datasource-es.yaml
Another unneeded -R on a cp command.

2022-03-04 17:19 UTC, gsmith-sas requested changes
See my comment about the get_sec_api function...it doesn't seem to be called and I don't know how the tenant exist function call can work without it.

2022-03-04 17:19 UTC, gsmith-sas commented on monitoring/bin/create_elasticsearch_datasource_tenant.sh
> +if [[ $(kibana_tenant_exists $tenant) == 1 ]]; then
You can simplify this syntax to:
`if ! kibana_tenant_exists "$ktenant"; then`

More importantly, I don't see a call to the get_sec_api function; this function must be called to establish the connection to Elasticsearch.  Is it being called somewhere else?

2022-03-04 17:19 UTC, gsmith-sas commented on monitoring/bin/create_elasticsearch_datasource_cluster.sh
> +if [ ! -z "$(kubectl get secret -n $MON_NS grafana-datasource-es -o custom-columns=:metadata.name --no-headers --ignore-not-found)"]; then
Mostly a "style" thing but you could replace `! -z` with `-n`...but we haven't adopted formal coding conventions or standardization.

2022-03-04 20:59 UTC, gsmith-sas requested changes
A small tweak to an error message but otherwise looks good.

2022-03-04 20:59 UTC, gsmith-sas commented on monitoring/bin/create_elasticsearch_datasource_tenant.sh
>    log_error "Unable to configure Elasticsearch data source.  The $tenant tenant has not been onboarded.";
Probably should include the "namespace" in the error message as well.  e.g.  _The tenant [foo] within the namespace [bar] has not been onboarded._

2022-03-08 17:51 UTC, merged