Fixed remove_monitoring_cluster script to correctly remove v4m-kubelet service
sassoftware/viya4-monitoring-kubernetes pull request #426
Opened 2022-11-07 21:15 UTC by cumcke

I forgot to include the Openshift in the previous CHANGELOG so I'm adding it in this pull request.

2022-11-07 22:24 UTC, gsmith-sas requested changes
A couple of tweaks/corrections to the wording of things.

2022-11-07 22:24 UTC, gsmith-sas commented on monitoring/bin/remove_monitoring_cluster.sh
> +log_verbose "Removing Kubelet"
According to the Kubernetes doc "The kubelet is the primary "node agent" that runs on each node."  Given that, this message migh alarm some folks.  I suggest updating the message to "Removing kubelet service".

2022-11-07 22:24 UTC, gsmith-sas commented on CHANGELOG.md
> +  * [FIX] - Deploy_monitoring_cluster script now correctly removes the v4m-kubelet service that is deployed by deploy_monitoring_cluster.
A little too verbose...and incorrect (it is the remove_monitoring_cluster script that does the removing).  Maybe something like  "[FIX] - Remove v4m-kubelet service when removing cluster-level metric monitoring components"

2022-11-08 16:52 UTC, gsmith-sas approved these changes
LGTM

2022-11-14 14:46 UTC, ceelias approved these changes

2022-11-14 15:57 UTC, merged