Replace ghost tunnel proxy
sassoftware/viya4-monitoring-kubernetes pull request #455
Opened 2023-01-25 15:20 UTC by ceelias

2023-03-09 21:14 UTC, ceelias commented on CHANGELOG.md
> +  * [UPGRADE] Introduced new **experimental** getlogs script written in python, to retrieve OpenSearch logs with filters and save to a file. Relevant documentation can be found [here](./logging/Expor
Added this small fix to the changelog entry for python get logs

2023-03-09 21:22 UTC, ceelias commented on samples/tls/path-based-ingress/monitoring/user-values-prom-operator.yaml
> +#     alertingEndpoints:
Now that I think about it, if a user had `TLS_ENABLE='true'` with `MON_TLS_PATH_INGRESS='true'` and did and update, without updating their configuration, prometheus alerts would not make their way to alertmanager. This section would need to be included. 

Thoughts?

2023-03-10 15:55 UTC, gsmith-sas requested changes
Looks good EXCEPT this change includes hard-coded references to the "monitoring" namespace.  That's not acceptable since users can (and do) deploy our monitoring components into different namespaces.

2023-03-10 15:55 UTC, gsmith-sas commented on monitoring/tls/prom-alertendpoint-host-https.yaml
> +        namespace: monitoring
We can't hard-code the namespace here.  Users can deploy our components into any namespace.

2023-03-10 15:55 UTC, gsmith-sas commented on monitoring/tls/prom-alertendpoint-path-https.yaml
> +      namespace: monitoring
See note above re: namespace

2023-03-13 19:04 UTC, gsmith-sas approved these changes
LGTM

2023-03-14 19:57 UTC, merged