Improvements to tracing solution
sassoftware/viya4-monitoring-kubernetes pull request #543
Opened 2023-08-22 14:35 UTC by ceelias

2023-08-22 19:23 UTC, ceelias commented on monitoring/bin/deploy_monitoring_openshift.sh
> +    ${AIRGAP_HELM_REPO}grafana/tempo
Will update this to use `chart2install`

2023-08-22 19:44 UTC, gsmith-sas requested changes
We need to double-check some Helm chart keys and reconcile these changes with those pushed in #540.

2023-08-22 19:44 UTC, gsmith-sas commented on monitoring/airgap/airgap-tempo-values.yaml
> +image:
Looking at the [Temp Helm chart, ](https://github.com/grafana/helm-charts/blob/6e2172f08b5539384734a42262f42836b8075fc5/charts/tempo/values.yaml#L16) it looks like the correct key  for this is NOT **image.repository** but **tempo.repository**.  Or, am I mis-reading things?

2023-08-22 19:44 UTC, gsmith-sas commented on monitoring/airgap/airgap-tempo-values.yaml
> +  - name: __AIRGAP_IMAGE_PULL_SECRET_NAME__
See above; the correct key may be **tempo.pullSecrets** (although I also see a **serviceAccount.imagePullSecret** key).  Please confirm we're setting the correct keys.

2023-08-22 19:44 UTC, gsmith-sas commented on monitoring/bin/deploy_monitoring_cluster.sh
> +  TEMPO_CHART_VERSION=${TEMPO_CHART_VERSION:-1.5.0}
Take a look at the changes I just merged in as part of #540.  They include some changes to this file.

2023-08-22 19:44 UTC, gsmith-sas commented on monitoring/bin/deploy_monitoring_openshift.sh
> +  TEMPO_CHART_VERSION=${TEMPO_CHART_VERSION:-1.5.0}
See note above re:changes merged in as part #540 .

2023-08-29 15:30 UTC, gsmith-sas requested changes
Looks good but needs some tweaks, especially wrt serviceAccounts and automounting of tokens.

2023-08-29 18:44 UTC, ceelias commented on monitoring/values-tempo.yaml
> +  enabled: false
From what I can tell this is sep from the 24 hour persistence, this one will create a PVC if enabled.

2023-08-30 17:48 UTC, ceelias commented on monitoring/openshift/tempo-values.yaml
> +  automountServiceAccountToken: true
Interestingly, I set this to false and I still see that the pods are mounting the service account. Am I missing something?

2023-08-31 15:41 UTC, gsmith-sas approved these changes
LGTM

2023-09-19 14:49 UTC, merged